

services:
    rent_db:
        image: postgres:15
        container_name: rent_db
        restart: always
        env_file:
            - .env
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASS}
        volumes:
            - db:/var/lib/postgresql/data
        ports:
            - "5433:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
            interval: 5s
            timeout: 3s
            retries: 10
    auth-module:
        build:
            context: .
            dockerfile: auth-module/Dockerfile
        container_name: auth-module
        restart: always
        depends_on:
            - rent_db
        env_file:
            - .env
        environment:

            DB_HOST: ${DB_HOST}
            DB_PORT: ${DB_PORT}
            DB_NAME: ${DB_NAME}
            DB_USER: ${DB_USER}
            DB_PASS: ${DB_PASS}

            SPRING_PROFILES_ACTIVE: docker



            # если  Eureka:
            # EUREKA_URI: ${EUREKA_URI}
        ports:
           - "${SERVER_PORT}:${SERVER_PORT}"

volumes:
    db:


